version: '2'
services:
  postgres:
    image: postgres:13
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=node_boilerplate
    volumes:
      - ./db/postgres/dev:/var/lib/postgresql/data
  postgres-test:
    image: postgres:13
    ports:
    - "5433:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=node_boilerplate_test
    volumes:
      - ./db/postgres/test:/var/lib/postgresql/data