version: '3'

services:
  mysql-dev:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: userauth_dev
    ports:
      - "3308:3306"
    volumes:
      - ./dumps:/docker-entrypoint-initdb.d

  mysql-test:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: userauth_test
    ports:
      - "3309:3306"
